name: bank_campaign_presentation

dependencies:
  - python=3.7
  - numpy=1.19.0
  - matplotlib=3.3.0
  - pandas=1.0.5
  - scikit-learn=0.23.1
  - seaborn=0.10.1
  - catboost=0.23.2
  - imbalanced-learn=0.7.0